### PR TITLE
Detect dangling ApprovalBuilder instances

### LINKED ISSUE #204: Handle tests thatcreate an `ApprovalBuilder` but do not trigger the actual approval
Right now to following test would happily pass no matter what the received value mal be:

```java
var result = "something different";

assertThat(result).isNotNull();
approve(result); // should conclude with a `by…()` method, like `byFile()`
```

IDEs would not know what approve means. They might complain if the assertion wasn't there, but with the assertion, there's no reason for IDEs or build tools to complain about this test.

The problem is, that the test code reads just fine and I'd prefer this to be a valid test, which would somehow conclude such dangling `ApprovalBuilder`s. E.g. calling `byFile()` on them as that can entirely rely on defaults and is probably the most popular way of finishing an `ApprovalBuilder`.

Should that prove impossible, it would be great if the test would fail with some meaningful error message like "Unfinished ApprovalBuilder …".

Finally, Idea warns about similar oversights regarding AssertJ (e.g. `assertThat(result)`). Maybe we can have something like that for ApperoveJ, too?

### PR DESCRIPTION
**Pull request by mkutz**
## Summary

- Detects `approve()` calls that are never concluded with a terminal method (`by()`, `byFile()`, `byValue()`)
- Adds `@ApprovalTest` annotation for test classes that enables a JUnit `AfterEachCallback` extension to check for dangling approvals after each test
- Tokens are scoped per thread via `ThreadLocal`, so parallel test execution is supported
- A shutdown hook provides a fallback warning when the extension is not active

### New public API

- `@ApprovalTest` — composed annotation to enable dangling approval detection on a test class
- `DanglingApprovalExtension` — JUnit `AfterEachCallback` (also usable directly via `@ExtendWith`)
- `DanglingApprovalError` — thrown when a dangling approval is detected

### Also

- Fixes a pre-existing bug: missing `return` in `ApprovalBuilder.by()` caused the approver to run twice for non-String values

Closes #204

## Test plan

- [x] `DanglingApprovalTrackerTest` covers: unconcluded token triggers error, concluded token does not, fluent chains share a token, multiple danglings, reset clears state
- [x] `DanglingApprovalErrorTest` verifies error message format
- [x] `ApprovalTestAnnotationTest` verifies the annotation includes `@ExtendWith`
- [x] `ApprovalBuilderTest` uses `@ApprovalTest` and all existing tests continue to pass
- [x] `./gradlew check` passes across all modules
- [x] Manual test on ApproveJ-workshop: single test and whole class execution correctly attribute the failure

### CODE REVIEW

File: modules/core/src/main/java/org/approvej/DanglingApprovalTracker.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+ * detect unconcluded tokens on that thread. A shutdown hook catches dangling tokens when no
+ * extension is active.
+ *
+ * <p>Thread-scoping ensures parallel test execution does not cause interference between tests.
+ */
+@NullMarked
+final class DanglingApprovalTracker {
+
+  private static final ThreadLocal<List<ApprovalToken>> threadTokens =
+      ThreadLocal.withInitial(ArrayList::new);
```
Comment (mkutz) [inline modules/core/src/main/java/org/approvej/DanglingApprovalTracker.java]: Addressed all four review comments:

1. **Memory leak** — `register()` prunes concluded tokens. Call site resolved eagerly to a single `String` so tokens are lightweight.
2. **Parallel execution** — Tokens scoped per thread via `ThreadLocal`. `checkAndReset()` only inspects the current thread's tokens. A separate global collection is kept solely for the shutdown hook fallback.
3. **volatile** — `concluded` is now `volatile`.
4. **Stack trace** — Call site resolved eagerly in `approve()` to a single `String` instead of storing the full stack trace array.
